package edu.engagement.server;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;

import org.apache.thrift.TException;
import org.postgresql.jdbc3.Jdbc3PoolingDataSource;

import edu.engagement.thrift.*;


/**
 * @author Michael Barnes
 *
 * The implemented engagement service generated by apache thrift. To regenerate
 * EngagementService.Iface navigate to the src/ folder and run the following:
 * <code>
 * 		thrift --gen java -out . engagement.thrift
 * </code>
 */
public class EngagementServiceImpl implements EngagementService.Iface {
	private EngagementServerDataAccessObject dao;
	
	/**
	 * Constructor for the engagement service. Initializes the data access
	 * object used for interacting with the database.
	 * 
	 * @param source	Database connection pool.
	 * @throws FileNotFoundException	This is thrown if the
	 *		server_sql_statements.properties file cannot be found in the
	 *		engagement-server/ directory.
	 * @throws IOException	  This is thrown if some I/O exception occurs
	 * 		loading the properties file.
	 */
	public EngagementServiceImpl(Jdbc3PoolingDataSource source) 
			throws FileNotFoundException, IOException {
		super();
		dao = new EngagementServerDataAccessObject(source);
	}

	
	/* (non-Javadoc)
	 * @see engagement.thrift#EngagmentService.syncEngagementInformation
	 */
	@Override
	public void syncEngagementInformation(EngagementInformation info)
			throws EngagementServiceUnavailable, TException {
		// TODO(mtbarnes): Make a logging system.
		System.out.print("Got data from: ");
		System.out.println(info.getGoogleId());
		dao.addEngagmentInfo(info);
	}

	/* (non-Javadoc)
	 * @see engagement.thrift#EngagementService.getEngagementInformation
	 */
	@Override
	public EngagementResponse getEngagmentInformation(EngagementQuery query)
			throws EngagementServiceUnavailable, TException {
		EngagementResponse resp = new EngagementResponse();
		for(Event e: query.getEvents()) {
			// TODO(mtbarnes): store event data for future processing.
			List<EegPower> powerData = dao.getPowerData(query.getGoogleId(), e);
			List<HeartRate> heartRateData = dao.getHeartRateData(
					query.getGoogleId(), e);
			EventInfo userEventInfo = new EventInfo();
			userEventInfo.setName(e.getName());
			userEventInfo.setAverageEngagement(
					calculateMeanEngagement(powerData));
			userEventInfo.setHeartRateStandardDeviation(
					calculateHeartRateStdDev(heartRateData));
			resp.addToEventInformation(userEventInfo);
		}
		return resp;
	}
	
	/**
	 * Calculates the mean engagement for the power data stored on the server.
	 * 
	 * @param powerData		The EEG information stored in the database.
	 * @return		The mean engagement value for the given EEG information.
	 */
	private double calculateMeanEngagement(List<EegPower> powerData) {
		double sum = 0.0;
		for(EegPower e: powerData) {
			sum += (double)(e.getAlpha() + e.getBeta()) / e.getTheta();
		}
		return sum / powerData.size();
	}
	
	/**
	 * Calculates the standard deviation for the heart rate data stored on the
	 * server.
	 * 
	 * @param heartRateData		The heart rate data stored in the database.
	 * @return		The standard deviation of the heart rate data given.
	 */
	private double calculateHeartRateStdDev(List<HeartRate> heartRateData) {
		double mean, variance, difMeanSqrd = 0.0, sum = 0.0;
		int size = heartRateData.size();
		for(HeartRate hr: heartRateData) {
			sum += hr.getBpm();
		}
		mean = sum / size;
		for(HeartRate hr: heartRateData) {
			difMeanSqrd += Math.pow(hr.getBpm() - mean, 2);
		}
		variance = difMeanSqrd / size;
		return Math.sqrt(variance);
	}
}
